Muscle_names_one_side={'addbrev','addlong','addmagProx','addmagMid',...
        'addmagDist','addmagIsch','bflh','bfsh','edl','ehl','fdl','fhl',...
        'gaslat','gasmed','gem','glmax1','glmax2','glmax3','glmed1',...
        'glmed2','glmed3','glmin1','glmin2','glmin3','grac','iliacus',...
        'pect','perbrev','perlong','pertert','piri','psoas','quadfem',...
        'recfem','sart','semimem','semiten','soleus','tfl',...
        'tibant','tibpost','vasint','vaslat',...
        'vasmed','ercspn_r','intobl_r','extobl_r'};
modelPath='D:\Gil\MeshesInAD\gaitWithKneeProsthesis\trackingSimulations_3D\OpenSimModel\subject_GC\JW All Body Model-scaled.osim';
MTparameters = getMTparameters(modelPath,Muscle_names_one_side);  
